[package]
name = "anoto_gui"
version = "0.3.0"
edition = "2024"

[dependencies]
argh = "0.1.13"
kornia = "0.1.9"
oxidize-pdf = "1.6.4"
rerun = "0.27.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
image = "0.25.9"
iced = { version = "0.13.1", features = ["highlighter", "system", "image"] }
bytesize = "2.3.1"
iced_test = "0.0.0"
rfd = "0.16.0"
bevy = "0.17.3"
bevy_shader = "0.17.3"
futures = "0.3"
futures-lite = "2.0"
bevy_ui_widgets = "0.17.3"
thiserror = "1.0"
